#!/bin/bash
#SBATCH --job-name=python
##SBATCH --account=torri
##SBATCH --partition=torri

#SBATCH --partition=shared

#SBATCH --time=0-03:00:00
#SBATCH --nodes=1 
#SBATCH  --tasks-per-node=1  
#SBATCH --cpus-per-task=1 #Each node has 47 CPUs
#SBATCH --mem=10G #GBTotal 180GB per node (180G/30 = 6G) #0 for full node memory

#SBATCH --error=pybash_job-%A.err
#SBATCH --output=pybash_job-%A.out
## Remote notification
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE,TIME_LIMIT_80
#SBATCH --mail-user=air673@hawaii.edu

mkdir -p job_out
#exec >> "job_out/py-$SLURM_ARRAY_TASK_ID.out" 2>&1 #don't use if you are piping to .out file below

#LOADING MODULES
module purge
module load lang/Anaconda3
source activate work #personal python custom environment

#PYTHON SETTINGS
export HDF5_USE_FILE_LOCKING=FALSE #disable HDF5 file locking
export PYTHONUNBUFFERED=TRUE #allows print statements during run

# --- RUNNING PYTHON ---

# ONE
mkdir -p job_out/pybash1
jupyter nbconvert --to script pybash1.ipynb
python -u pybash1.py $SLURM_ARRAY_TASK_ID \
     > job_out/pybash1/py-${SLURM_ARRAY_TASK_ID}.out 2>&1

# TWO
#mkdir -p job_out/pybash2
#python -u pybash2.py $SLURM_ARRAY_TASK_ID \
#    > job_out/pybash2/py-${SLURM_ARRAY_TASK_ID}.out 2>&1
