#!/bin/bash
#SBATCH --job-name=python
#SBATCH --array=1-20 #%+number after to limit number of of runs at a time
##SBATCH --account=<account>
##SBATCH --partition=<account>
#SBATCH --partition=shared

#SBATCH --time=0-03:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=1 #Each node has 47 CPUs
#SBATCH --mem=10G #GBTotal 180GB per node (180G/30 = 6G) #0 for full node memory

#SBATCH --error=pybash_job-%A_%a.err
#SBATCH --output=pybash_job-%A_%a.out
## Remote notification
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE,TIME_LIMIT_80
#SBATCH --mail-user=<email@address.com>

# Run everything from the sbatch folder (where this script was submitted)
cd "$SLURM_SUBMIT_DIR"
mkdir -p job_out

#LOADING MODULES
module purge
module load lang/Anaconda3
source activate work #personal python custom environment

#PYTHON SETTINGS
export HDF5_USE_FILE_LOCKING=FALSE #disable HDF5 file locking
export PYTHONUNBUFFERED=TRUE #allows print statements during run

# --- RUNNING PYTHON ---
# (convert first: jupyter nbconvert --to script ../<name>.ipynb --output-dir .)

# ONE
scriptName=PythonScript1
mkdir -p job_out/${scriptName}
python -u ${scriptName}.py $SLURM_ARRAY_TASK_ID \
     > job_out/${scriptName}/py-${SLURM_ARRAY_TASK_ID}.out 2>&1

# TWO
#scriptName=PythonScript2
#mkdir -p job_out/${scriptName}
#python -u ${scriptName}.py $SLURM_ARRAY_TASK_ID \
#     > job_out/${scriptName}/py-${SLURM_ARRAY_TASK_ID}.out 2>&1